spring.application.name=lxp

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:lxp-test
spring.datasource.username=sa
spring.datasource.password=

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:demo-data.sql
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=4d553a82c87c2a2e0b7000d63eb926f3ef75fd528977b9c956efcec692845953
jwt.access-token-validity-milliseconds=3600000
jwt.refresh-token-validity-milliseconds=864000000
